# compose.yml
version: '3.1'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
       - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 15s
      retries: 5